### ISSUE TITLE
Bounds in objective MINIMIZE_TIME

### ISSUE THREAD

**Issue by Steakkk** [pyomeca/bioptim#239]
Adding bounds in objective MINIMIZE_TIME gives the following error.

```Traceback (most recent call last):
  File "/home/steak/afs/lab_canada/JumperOCP/optimization_biorbdOptim/jumper2phases.py", line 299, in <module>
    ocp = prepare_ocp(
  File "/home/steak/afs/lab_canada/JumperOCP/optimization_biorbdOptim/jumper2phases.py", line 220, in prepare_ocp
    return OptimalControlProgram(
  File "/home/steak/afs/lab_canada/JumperOCP/optimization_biorbdOptim/bioptim/misc/optimal_control_program.py", line 323, in __init__
    self.update_objectives(objective_functions)
  File "/home/steak/afs/lab_canada/JumperOCP/optimization_biorbdOptim/bioptim/misc/optimal_control_program.py", line 658, in update_objectives
    self.__modify_penalty(objective, "objective_functions")
  File "/home/steak/afs/lab_canada/JumperOCP/optimization_biorbdOptim/bioptim/misc/optimal_control_program.py", line 717, in __modify_penalty
    ObjectiveFunction.add_or_replace(self, self.nlp[phase_idx], new_penalty)
  File "/home/steak/afs/lab_canada/JumperOCP/optimization_biorbdOptim/bioptim/limits/objective_functions.py", line 218, in add_or_replace
    PenaltyFunctionAbstract.add_or_replace(ocp, nlp, objective)
  File "/home/steak/afs/lab_canada/JumperOCP/optimization_biorbdOptim/bioptim/limits/penalty.py", line 497, in add_or_replace
    penalty_function(penalty, ocp, nlp, t, x, u, nlp.p, **penalty.params)
TypeError: minimize_time() got an unexpected keyword argument 'min_bound'

**Comment by pariterre** [comment]
This should fix this issue, #246 
Please note that I just noticed that Lagrange cannot be used with bounds. It must be Mayer or Constraints to add bounds!
