### ISSUE TITLE
Broken conversion of joints angles to markers in Casadi Function

### ISSUE THREAD

**Issue by vennand** [pyomeca/bioptim#258]
Conversion of joint angles to markers using: 
`cas.Function("makers_kyn", [q], [biorbd_model.markers(q)]).expand()`
now returns the following error in example mhe.py

```
/home/andre/bioptim/examples/moving_horizon_estimation/mhe.py
Traceback (most recent call last):
  File "/home/andre/bioptim/examples/moving_horizon_estimation/mhe.py", line 200, in <module>
    X_, Y_, Y_N_, U_ = generate_data(biorbd_model, Tf, X0, T_max, N, noise_std, SHOW_PLOTS=False)
  File "/home/andre/bioptim/examples/moving_horizon_estimation/mhe.py", line 47, in generate_data
    markers_kyn = cas.Function("makers_kyn", [q], [biorbd_model.markers(q)]).expand()
  File "/home/andre/anaconda3/envs/BioOptim_current/lib/python3.8/site-packages/casadi/casadi.py", line 13558, in __init__
    this = _casadi.new_Function(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_Function'.
  Possible prototypes are:
    Function()
    Function(str)
    Function(Function)
    Function(str,[SX],[SX],dict)
    Function(str,[MX],[MX],dict)
    Function(str,dict:SX,[str],[str],dict)
    Function(str,dict:MX,[str],[str],dict)
    Function(str,[SX],[SX],[str],[str],dict)
    Function(str,[MX],[MX],[str],[str],dict)
  You have: '(str,[MX],[(NodeSegment,NodeSegment,NodeSegment,NodeSegment,NodeSegment)])
```

Using
`biorbd.to_casadi_func("makers_kyn", biorbd_model.markers, q)`
seems to be a working alternative

**Comment by pariterre** [comment]
Fixed in #287 
Thanks for reporting!
