### ISSUE TITLE
get_data with one phase

### ISSUE THREAD

**Issue by EveCharbie** [pyomeca/bioptim#283]
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/Trampo_bioptim/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-e80e6f03d279>", line 1, in <module>
    Solution_data = Data.get_data(ocp, sol, get_states=True)
  File "/home/user/Documents/Programmation/BiorbdOptim/bioptim/misc/data.py", line 235, in get_data
    data_states, data_controls, data_parameters = Data.get_data_object(
  File "/home/user/Documents/Programmation/BiorbdOptim/bioptim/misc/data.py", line 311, in get_data_object
    phase_time[i] = data_parameters["time"][cmp, 0]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by pariterre** [comment]
Get data will be completely removed in a VERY near future. Stay tuned!

**Comment by pariterre** [comment]
Please have a look at #285 to see if it solved your problem!
