### ISSUE TITLE
Bound plotting odd phenomenon with ocp.add_plot()

### ISSUE THREAD

**Issue by jcllau** [pyomeca/bioptim#563]
Hello!

From my previous issue [here](https://github.com/pyomeca/bioptim/issues/554), my last messages were related to creating bounds in a custom plot, and I said I found a way to do it by setting `bounds=x_bounds[0][0:nDof]`.

I actually have 6 of these ocp.addplot(...) lines in my code because I want to plot q_firstphase, q_secondphase, qdot_firstphase, qdot_secondphase, tau_firstphase, and tau_secondphase. Without the bounds, the graphs with custom names work. With pseudo code for simplification, this is how the sequence looks like:

```
# Sequence 1
ocp.add_plot( things for custom plot q, legend=[...], bounds=x_bounds[**0**][0:nDof] ) # let's call this line q_p0
ocp.add_plot( things for custom plot q, legend=[...], bounds=x_bounds[**1**][0:nDof] ) # let's call this q_p1
ocp.add_plot( things for custom plot qdot, legend=[...], bounds=x_bounds[**0**][nDof:nDof*2] ) # let's call this qdot_p0
ocp.add_plot( things for custom plot qdot, legend=[...], bounds=x_bounds[**1**][nDof:nDof*2] ) # let's call this qdot_p1
ocp.add_plot( things for custom plot u, legend=[...], bounds=u_bounds[**0**][0:nTau] ) # let's call this u_p0
ocp.add_plot( things for custom plot u, legend=[...], bounds=u_bounds[**1**][0:nTau] ) # let's call this u_p1
```
With Sequence 1, the bounds for all six add_plots work *but* q_p1, and the terminal gives the following error:
```
Process Process-1:
Traceback (most recent call last):
  File "/home/jcllau/anaconda3/envs/bioptim/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/jcllau/anaconda3/envs/bioptim/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jcllau/anaconda3/envs/bioptim/lib/python3.10/site-packages/bioptim-2.1.3-py3.10.egg/bioptim/gui/plot.py", line 1142, in __call__
    self.plot = PlotOcp(self.ocp, **show_options)
  File "/home/jcllau/anaconda3/envs/bioptim/lib/python3.10/site-packages/bioptim-2.1.3-py3.10.egg/bioptim/gui/plot.py", line 266, in __init__
    self.__create_plots()
  File "/home/jcllau/anaconda3/envs/bioptim/lib/python3.10/site-packages/bioptim-2.1.3-py3.10.egg/bioptim/gui/plot.py", line 408, in __create_plots
    if y_min.__array__()[0] < y_min_all[var_idx][ctr]:
IndexError: list index out of range

```
So then, I moved around the sequence of when the plots are called, such that it's qdot, u, then q
```
# Sequence 2
qdot_p0
qdot_p1
u_p0
u_p1
q_p0
q_p1
```
In Sequence 2, the bounds for qdot_p1, which worked before, yields the same error described above. Meanwhile, the bounds for q_p1, which didn't work in Sequence 1, works here. So then, I moved the sequence again so that it's u, q, then qdot.
```
# Sequence 3
u_p0
u_p1
q_p0
q_p1
qdot_p0
qdot_p1
```
In Sequence 3, the bounds for u_p1 caused that error, but q_p1 and qdot_p1 bounds work fine.

I'm not sure what's causing this to happen. The problem doesn't seem to be the way my multiphase x_bounds and u_bounds are created either, since even before these tests, the bounds show up when I use the non-custom ocp plotting.

**Comment by Ipuch** [comment]
Could you provide your script?  It would help to debug. This is quite an advanced question now ;)

**Comment by jcllau** [comment]
Yes. Is there an email I can send you the script? :)

**Comment by Ipuch** [comment]
You can post it here. Try to minimize the code as much as possible ton reproduce the bug.

**Comment by jcllau** [comment]
Ok. I will send it to you within the next few days. Sorry I'm in the middle of fixing and cleaning my code :)

**Comment by jcllau** [comment]
Funnily enough, in the process of cleaning up my code (to make it neater before sharing), the bound plotting issue is no longer happening. Would you still like to see the cleaned-up code just in case?

**Comment by jcllau** [comment]
This is the main file:
```
# Import things
from cmath import pi
from typing import Union
from casadi import MX
import biorbd_casadi as biorbd
from bioptim import *
from functions_for_simplified_code import *
from matplotlib import pyplot as plt

# Custom plotting functions
def custom_plot_q(x, nDof):
    return x[0:nDof, :]

def custom_plot_qdot(x, nDof):
    return x[nDof:nDof*2, :]

def custom_plot_u(x, nTau):
    return x[0:nTau, :]

# Load model
biorbd_model_path0 = "bioptim_phase0model.bioMod"
biorbd_model_path1 = "bioptim_phase1model.bioMod"
model = biorbd.Model(biorbd_model_path0), biorbd.Model(biorbd_model_path1)
nDof = model[0].nbQ()
nTau = model[0].nbGeneralizedTorque()

# Set parameters
n_phases = 2
n_shooting = 50, 50
final_time = 2, 2
time_min = 1, 1
time_max = 2.5, 2.5
tau_min, tau_max, tau_init = -500, 500, 0

# Dynamics
dynamics = DynamicsList()
dynamics.add(DynamicsFcn.TORQUE_DRIVEN, with_contact=True, phase=0)
dynamics.add(DynamicsFcn.TORQUE_DRIVEN, with_contact=True, phase=1)

# Objective Function
objective_functions = ObjectiveList()
objective_functions.add(ObjectiveFcn.Lagrange.MINIMIZE_CONTROL, key="tau", phase=0, quadratic=True)
objective_functions.add(ObjectiveFcn.Lagrange.MINIMIZE_CONTROL, key="tau", phase=1, quadratic=True)


# Constraints
constraints = ConstraintList()
# -------------- Phase 0
# ------------------------ 1) Feet on ground
constraints.add(
    ConstraintFcn.TRACK_CONTACT_FORCES,
    min_bound=0.01,
    max_bound=biorbd.np.inf,
    node=Node.ALL,
    contact_index=4,
    phase=0,
)
constraints.add(
    ConstraintFcn.TRACK_CONTACT_FORCES,
    min_bound=0.01,
    max_bound=biorbd.np.inf,
    node=Node.ALL,
    contact_index=2,
    phase=0,
)
constraints.add(
    ConstraintFcn.NON_SLIPPING,
    node=Node.ALL,
    normal_component_idx=2,
    tangential_component_idx=3,
    static_friction_coefficient=0.3,
    phase=0,
)
constraints.add(ConstraintFcn.TRACK_MARKERS, node=Node.ALL, marker_index=2, axes=Axis.Z, phase=0, weight=10)
constraints.add(ConstraintFcn.TRACK_MARKERS, node=Node.ALL, marker_index=3, axes=[Axis.Y, Axis.Z], phase=0, weight=10)
constraints.add(ConstraintFcn.TRACK_MARKERS_VELOCITY, node=Node.START, marker_index=2, phase=0, weight=10)
constraints.add(ConstraintFcn.TRACK_MARKERS_VELOCITY, node=Node.START, marker_index=3, phase=0, weight=10)

# ------------------------ 2) Seat contact
constraints.add(
    ConstraintFcn.TRACK_CONTACT_FORCES,
    min_bound=0.01,
    max_bound=biorbd.np.inf,
    node=Node.ALL_SHOOTING,
    contact_index=0,
    phase=0,
)
constraints.add(
    ConstraintFcn.NON_SLIPPING,
    node=Node.ALL_SHOOTING,
    normal_component_idx=0,
    tangential_component_idx=1,
    static_friction_coefficient=0.3,
    phase=0,
)
# ------------------------ 3) Seat lifting condition
constraints.add(
    ConstraintFcn.TRACK_CONTACT_FORCES,
    min_bound=0,
    max_bound=0.01,
    node=Node.END,
    contact_index=0,
    phase=0,
)

# -------------- Phase 1
# ------------------------ 1) Feet on ground
constraints.add(
    ConstraintFcn.TRACK_CONTACT_FORCES,
    min_bound=0.01,
    max_bound=biorbd.np.inf,
    node=Node.ALL,
    contact_index=2,
    phase=1,
)
constraints.add(
    ConstraintFcn.TRACK_CONTACT_FORCES,
    min_bound=0.01,
    max_bound=biorbd.np.inf,
    node=Node.ALL,
    contact_index=0,
    phase=1,
)
constraints.add(
    ConstraintFcn.NON_SLIPPING,
    node=Node.ALL,
    normal_component_idx=0,
    tangential_component_idx=1,
    static_friction_coefficient=0.3,
    phase=1,
)
constraints.add(ConstraintFcn.TRACK_MARKERS, node=Node.ALL, marker_index=2, axes=Axis.Z, phase=1, weight=10)
constraints.add(ConstraintFcn.TRACK_MARKERS, node=Node.ALL, marker_index=3, axes=[Axis.Y, Axis.Z], phase=1, weight=10)
constraints.add(ConstraintFcn.TRACK_MARKERS_VELOCITY, node=Node.START, marker_index=2, phase=1, weight=10)
constraints.add(ConstraintFcn.TRACK_MARKERS_VELOCITY, node=Node.START, marker_index=3, phase=1, weight=10)

# Path constraint
x_bounds = BoundsList()
x_bounds.add(bounds=QAndQDotBounds(model[0]))
x_bounds.add(bounds=QAndQDotBounds(model[1]))
x_bounds = setQAndQDotBounds(x_bounds)

# State initial guess
x_init = InitialGuessList()
x_init.add([0] * (model[0].nbQ() + model[0].nbQdot()))
x_init.add([0] * (model[1].nbQ() + model[1].nbQdot()))
x_init = setStateInitialGuess(x_init)

# Define control path constraint
u_bounds = BoundsList()
u_bounds.add([0] * model[0].nbGeneralizedTorque(), [0] * model[0].nbGeneralizedTorque())
u_bounds.add([0] * model[1].nbGeneralizedTorque(), [0] * model[1].nbGeneralizedTorque())
u_bounds = setControlBounds(u_bounds)

# Control initial guess
u_init = InitialGuessList()
u_init.add([tau_init] * model[0].nbGeneralizedTorque())
u_init.add([tau_init] * model[1].nbGeneralizedTorque())

# Phase transition
phase_transitions = PhaseTransitionList()
phase_transitions.add(PhaseTransitionFcn.CONTINUOUS, phase_pre_idx=0)


# OCP
print("preparing ocp")
ocp = OptimalControlProgram(
    model[:n_phases],
    dynamics,
    n_shooting[:n_phases],
    final_time[:n_phases],
    x_init,
    u_init,
    x_bounds,
    u_bounds,
    objective_functions,
    constraints,
    ode_solver=OdeSolver.RK4(),
    control_type=ControlType.CONSTANT,
    n_threads=6,
)

# Plots
ocp.add_plot(
    "custom plot u", lambda t, x, u, p: custom_plot_u(u, nTau), phase=0,
    legend=[
        "pelvismpt transY", "pelvismpt transZ", "pelvismpt rotX",
        "xiphoid rotX", "xiphoid rotY",
        "hip rotX", "knee rotX", "ankle rotX",
        "left shoulder rotX", "left shoulder rotY", "left elbow rotX",
        "right shoulder rotX", "right shoulder rotY", "right elbow rotX"
    ],
    bounds=u_bounds[0][0:nTau]
)
ocp.add_plot(
    "custom plot u", lambda t, x, u, p: custom_plot_u(u, nTau), phase=1,
    legend=[
        "pelvismpt transY", "pelvismpt transZ", "pelvismpt rotX",
        "xiphoid rotX", "xiphoid rotY",
        "hip rotX", "knee rotX", "ankle rotX",
        "left shoulder rotX", "left shoulder rotY", "left elbow rotX",
        "right shoulder rotX", "right shoulder rotY", "right elbow rotX"
    ],
    bounds=u_bounds[1][0:nTau]
)
ocp.add_plot(
    "custom plot q", lambda t, x, u, p: custom_plot_q(x, nDof), phase=0,
    legend=[
        "pelvismpt transY", "pelvismpt transZ", "pelvismpt rotX",
        "xiphoid rotX", "xiphoid rotY",
        "hip rotX", "knee rotX", "ankle rotX",
        "left shoulder rotX", "left shoulder rotY", "left elbow rotX",
        "right shoulder rotX", "right shoulder rotY", "right elbow rotX"
    ],
    bounds=x_bounds[0][0:nDof]
)
ocp.add_plot(
    "custom plot q", lambda t, x, u, p: custom_plot_q(x, nDof), phase=1,
    legend=[
        "pelvismpt transY", "pelvismpt transZ", "pelvismpt rotX",
        "xiphoid rotX", "xiphoid rotY",
        "hip rotX", "knee rotX", "ankle rotX",
        "left shoulder rotX", "left shoulder rotY", "left elbow rotX",
        "right shoulder rotX", "right shoulder rotY", "right elbow rotX"
    ],
    bounds=x_bounds[1][0:nDof]
)
ocp.add_plot(
    "custom plot qdot", lambda t, x, u, p: custom_plot_qdot(x, nDof), phase=0,
    legend=[
        "pelvismpt transY", "pelvismpt transZ", "pelvismpt rotX",
        "xiphoid rotX", "xiphoid rotY",
        "hip rotX", "knee rotX", "ankle rotX",
        "left shoulder rotX", "left shoulder rotY", "left elbow rotX",
        "right shoulder rotX", "right shoulder rotY", "right elbow rotX"
    ],
    bounds=x_bounds[0][nDof:nDof*2]
)
ocp.add_plot(
    "custom plot qdot", lambda t, x, u, p: custom_plot_qdot(x, nDof), phase=1,
    legend=[
        "pelvismpt transY", "pelvismpt transZ", "pelvismpt rotX",
        "xiphoid rotX", "xiphoid rotY",
        "hip rotX", "knee rotX", "ankle rotX",
        "left shoulder rotX", "left shoulder rotY", "left elbow rotX",
        "right shoulder rotX", "right shoulder rotY", "right elbow rotX"
    ],
    bounds=x_bounds[1][nDof:nDof*2]
)

ocp.add_plot_penalty(CostType.ALL)
ocp.print(to_console=False, to_graph=False)
solver_ipopt = Solver.IPOPT(show_online_optim=True)
solver_ipopt.set_convergence_tolerance(1e-10)
solver_ipopt.set_maximum_iterations(1000)
solver_ipopt.show_options = dict(show_bounds=True)
sol = ocp.solve(solver=solver_ipopt)
sol.detailed_cost_values()
sol.print_cost()
# sol.graphs(automatically_organize=False)
sol.animate(n_frames=100)
```

And below is another py file that's called by the main file:
```
pi = 3.14159265359

def setQAndQDotBounds(x_bounds):
    # lumpedpelvismpt transY 
    x_bounds[0].min[0, :] = -0.7
    x_bounds[0].max[0, :] = 0.3
    x_bounds[1].min[0, :-1] = -0.7
    x_bounds[1].max[0, :-1] = 0.3
    x_bounds[1][0, -1] = 0

    # lumpedpelvismpt transZ 
    x_bounds[0][1, 0] = 0.521588727 - 0.81899
    x_bounds[0].min[1, 1:] = 0.521588727 - 0.81899
    x_bounds[0].max[1, 1:] = 0
    x_bounds[1].min[1, :-1] = 0.521588727 - 0.81899
    x_bounds[1].max[1, :-1] = 0
    x_bounds[1][1, -1] = 0

    # lumbo-sacral rotX Q
    x_bounds[0].min[2, :] = -pi
    x_bounds[0].max[2, :] = pi
    x_bounds[1].min[2, :-1] = -pi
    x_bounds[1].max[2, :-1] = pi
    x_bounds[1][2, -1] = 0

    # xiphoid RX Q
    x_bounds[0][3, 0] = 0
    x_bounds[0].min[3, 1:] = -0.1
    x_bounds[0].max[3, 1:] = 0.1
    x_bounds[1].min[3, :-1] = -0.1
    x_bounds[1].max[3, :-1] = 0.1
    x_bounds[1][3, -1] = 0

    # xiphoid RY Q
    x_bounds[0][4, 0] = 0
    x_bounds[0].min[4, 1:] = -0.1
    x_bounds[0].max[4, 1:] = 0.1
    x_bounds[1].min[4, :-1] = -0.1
    x_bounds[1].max[4, :-1] = 0.1
    x_bounds[1][4, -1] = 0

    # hips RX Q
    x_bounds[0].min[5, :] = -0.02
    x_bounds[0].max[5, :] = 2.474
    x_bounds[1].min[5, :-1] = -0.02
    x_bounds[1].max[5, :-1] = 2.474
    x_bounds[1][5, -1] = 0

    # knees RX Q
    x_bounds[0].min[6, :] = -1.8068
    x_bounds[0].max[6, :] = 0.02
    x_bounds[1].min[6, :-1] = -1.8068
    x_bounds[1].max[6, :-1] = 0.02
    x_bounds[1][6, -1] = 0

    # ankles RX Q
    x_bounds[0].min[7, :] = -0.02
    x_bounds[0].max[7, :] = 0.8247
    x_bounds[1].min[7, :-1] = -0.02
    x_bounds[1].max[7, :-1] = 0.8247
    x_bounds[1][7, -1] = 0

    # LEFT shoulder RX Q
    x_bounds[0][8, 0] = 0
    x_bounds[0].min[8, 1:] = -pi/4
    x_bounds[0].max[8, 1:] = 3*pi/4
    x_bounds[1].min[8, :-1] = -pi/4
    x_bounds[1].max[8, :-1] = 3*pi/4
    x_bounds[1][8, -1] = 0

    # LEFT shoulder RY Q
    x_bounds[0][9, 0] = pi/6
    x_bounds[0].min[9, 1:] = pi/6
    x_bounds[0].max[9, 1:] = 5*pi/6
    x_bounds[1].min[9, :-1] = pi/6
    x_bounds[1].max[9, :-1] = 5*pi/6
    x_bounds[1][9, -1] = pi/6

    # LEFT elbow RX Q
    x_bounds[0][10, 0] = 0
    x_bounds[0].min[10, 1:] = 0
    x_bounds[0].max[10, 1:] = 1.2
    x_bounds[1].min[10, :-1] = 0
    x_bounds[1].max[10, :-1] = 1.2
    x_bounds[1][10, -1] = 0

    # RIGHT shoulder RX Q
    x_bounds[0][11, 0] = 0
    x_bounds[0].min[11, 1:] = -pi/4
    x_bounds[0].max[11, 1:] = 3*pi/4
    x_bounds[1].min[11, :-1] = -pi/4
    x_bounds[1].max[11, :-1] = 3*pi/4
    x_bounds[1][11, -1] = 0

    # RIGHT shoulder RY Q (mirrored from LEFT shoulder RY)
    x_bounds[0][12, 0] = -pi/6
    x_bounds[0].min[12, 1:] = -5*pi/6
    x_bounds[0].max[12, 1:] = -pi/6
    x_bounds[1].min[12, :-1] = -5*pi/6
    x_bounds[1].max[12, :-1] = -pi/6
    x_bounds[1][12, -1] = -pi/6

    # RIGHT elbow RX Q
    x_bounds[0][13, 0] = 0
    x_bounds[0].min[13, 1:] = 0
    x_bounds[0].max[13, 1:] = 1.2
    x_bounds[1].min[13, :-1] = 0
    x_bounds[1].max[13, :-1] = 1.2
    x_bounds[1][13, -1] = 0

    # Velocities
    x_bounds[0][14:, 0] = 0
    x_bounds[0].min[14:, 1:] = -10
    x_bounds[0].max[14:, 1:] = 10
    x_bounds[1].min[14:, :-1] = -10
    x_bounds[1].max[14:, :-1] = 10
    x_bounds[1][14:, -1] = 0

    return x_bounds

def setStateInitialGuess(x_init):
    x_init[0][0] = -0.3442
    x_init[0][1] = 0.521588727 - 0.81899
    x_init[0][2] = 0
    x_init[0][3] = 0
    x_init[0][4] = 0
    x_init[0][5] = pi/2
    x_init[0][6] = -pi/2
    x_init[0][7] = 0
    x_init[0][8] = pi/2
    x_init[0][9] = 0.3
    x_init[0][10] = 0
    x_init[0][11] = pi/2
    x_init[0][12] = -0.3
    x_init[0][13] = 0

    # Velocities
    x_init[0][14:] = 0

    return x_init

def setControlBounds(u_bounds):
    # Floating base tau = 0
    u_bounds[0][0:3, :] = 0
    u_bounds[1][0:3, :] = 0

    # xiphoid RX
    u_bounds[0][3, 0] = 0
    u_bounds[0].min[3, 1:] = -50
    u_bounds[0].max[3, 1:] = 50
    u_bounds[1].min[3, :-1] = -50
    u_bounds[1].max[3, :-1] = 50
    u_bounds[1][3, -1] = 0

    # xiphoid RY
    u_bounds[0][4, 0] = 0
    u_bounds[0].min[4, 1:] = -50
    u_bounds[0].max[4, 1:] = 50
    u_bounds[1].min[4, :-1] = -50
    u_bounds[1].max[4, :-1] = 50
    u_bounds[1][4, -1] = 0

    # hips RX
    u_bounds[0][5, 0] = 0
    u_bounds[0].min[5, 1:] = -500
    u_bounds[0].max[5, 1:] = 500
    u_bounds[1].min[5, :-1] = -500
    u_bounds[1].max[5, :-1] = 500
    u_bounds[1][5, -1] = 0

    # knees RX
    u_bounds[0][6, 0] = 0
    u_bounds[0].min[6, 1:] = -500
    u_bounds[0].max[6, 1:] = 500
    u_bounds[1].min[6, :-1] = -500
    u_bounds[1].max[6, :-1] = 500
    u_bounds[1][6, -1] = 0

    # ankles RX
    u_bounds[0][7, 0] = 0
    u_bounds[0].min[7, 1:] = -500
    u_bounds[0].max[7, 1:] = 500
    u_bounds[1].min[7, :-1] = -500
    u_bounds[1].max[7, :-1] = 500
    u_bounds[1][7, -1] = 0

    # left shoulder RX
    u_bounds[0][8, 0] = 0
    u_bounds[0].min[8, 1:] = -50
    u_bounds[0].max[8, 1:] = 50
    u_bounds[1].min[8, :-1] = -50
    u_bounds[1].max[8, :-1] = 50
    u_bounds[1][8, -1] = 0

    # left shoulder RY
    u_bounds[0][9, 0] = 0
    u_bounds[0].min[9, 1:] = -50
    u_bounds[0].max[9, 1:] = 50
    u_bounds[1].min[9, :-1] = -50
    u_bounds[1].max[9, :-1] = 50
    u_bounds[1][9, -1] = 0

    # left elbow RX
    u_bounds[0][10, 0] = 0
    u_bounds[0].min[10, 1:] = -50
    u_bounds[0].max[10, 1:] = 50
    u_bounds[1].min[10, :-1] = -50
    u_bounds[1].max[10, :-1] = 50
    u_bounds[1][10, -1] = 0

    # right shoulder RX
    u_bounds[0][11, 0] = 0
    u_bounds[0].min[11, 1:] = -50
    u_bounds[0].max[11, 1:] = 50
    u_bounds[1].min[11, :-1] = -50
    u_bounds[1].max[11, :-1] = 50
    u_bounds[1][11, -1] = 0

    # right shoulder RY
    u_bounds[0][12, 0] = 0
    u_bounds[0].min[12, 1:] = -50
    u_bounds[0].max[12, 1:] = 50
    u_bounds[1].min[12, :-1] = -50
    u_bounds[1].max[12, :-1] = 50
    u_bounds[1][12, -1] = 0

    # right elbow RX
    u_bounds[0][13, 0] = 0
    u_bounds[0].min[13, 1:] = -50
    u_bounds[0].max[13, 1:] = 50
    u_bounds[1].min[13, :-1] = -50
    u_bounds[1].max[13, :-1] = 50
    u_bounds[1][13, -1] = 0

    return u_bounds
```
