### ISSUE TITLE
Defining multi node constraints with MultinodeConstraint is not supported

### ISSUE THREAD

**Issue by EveCharbie** [pyomeca/bioptim#690]
Replacing:
```
    multinode_constraints = MultinodeConstraintList()
    multinode_constraints.add(
        MultinodeConstraintFcn.STATES_EQUALITY,
        nodes_phase=(0, 2, 2),
        nodes=(Node.START, Node.START, Node.MID),
        key="all",
    )
```
with:
```
    from bioptim import MultinodeConstraint
    multinode_constraints = MultinodeConstraint(
        MultinodeConstraintFcn.STATES_EQUALITY,
        nodes_phase=(0, 2, 2),
        nodes=(Node.START, Node.START, Node.MID),
        key="all",
    )
```
Gives the following error:
```
Traceback (most recent call last):
  File "/snap/pycharm-community/332/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/332/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/charbie/Documents/Programmation/BiorbdOptim/bioptim/examples/getting_started/example_multinode_constraints.py", line 231, in <module>
    main()
  File "/home/charbie/Documents/Programmation/BiorbdOptim/bioptim/examples/getting_started/example_multinode_constraints.py", line 220, in main
    ocp = prepare_ocp(biorbd_model_path="models/cube.bioMod", n_shootings=(100, 300, 100))
  File "/home/charbie/Documents/Programmation/BiorbdOptim/bioptim/examples/getting_started/example_multinode_constraints.py", line 133, in prepare_ocp
    multinode_constraints = MultinodeConstraint(
  File "/home/charbie/Documents/Programmation/BiorbdOptim/bioptim/limits/multinode_constraint.py", line 19, in __init__
    super(MultinodeConstraint, self).__init__(MultinodeConstraintFcn, *args, **kwargs)
TypeError: MultinodePenalty.__init__() got multiple values for argument 'nodes'
python-BaseException
Backend QtAgg is interactive backend. Turning interactive mode on.
```

**Comment by pariterre** [comment]
You should always be using List anyway. We are moving forward removing every instances of non List stuff in the API
