### ISSUE TITLE
pyQt examples - error with Content search

### ISSUE THREAD

**Issue by mickaelbegon** [pyomeca/bioptim#810]
When running python -m bioptim.examples
and choosing "Content search"
error message:

Traceback (most recent call last):
  File "/Users/mickaelbegon/Documents/GIT/bioptim/bioptim/examples/__main__.py", line 576, in filterByContent
    contents = self.getExampleContent(filename).lower()
  File "/Users/mickaelbegon/Documents/GIT/bioptim/bioptim/examples/__main__.py", line 703, in getExampleContent
    with open(filename, "r") as currentFile:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mickaelbegon/Documents/GIT/bioptim/acados/static_arm.py'

**Comment by mickaelbegon** [comment]
I opened draft PR #1068. Content search now preserves nested example directories and resolves files from the `bioptim/examples` module directory instead of `os.getcwd()`. The regression test verifies that every declared example path exists and passes locally, and `git diff --check` is clean. @pariterre, the implementation is working locally and ready for review; CI is running on the PR.
