### ISSUE TITLE
Can't plot graphs when using mapping?

### ISSUE THREAD

**Issue by Erdnaxela3** [pyomeca/bioptim#818]
On bioptim tag 3.2.0

Traceback (most recent call last):
  File "/home/aweng/afs/bioptim_gui/gui/test/straight_0_12012024.py", line 606, in main
    sol.graphs(show_bounds=True)
  File "/home/aweng/anaconda3/envs/bioptim/lib/python3.12/site-packages/bioptim-3.2.0-py3.12.egg/bioptim/optimization/solution/solution.py", line 883, in graphs
    plot_ocp.update_data(self.vector)
  File "/home/aweng/anaconda3/envs/bioptim/lib/python3.12/site-packages/bioptim-3.2.0-py3.12.egg/bioptim/gui/plot.py", line 712, in update_data
    self.__update_axes()
  File "/home/aweng/anaconda3/envs/bioptim/lib/python3.12/site-packages/bioptim-3.2.0-py3.12.egg/bioptim/gui/plot.py", line 862, in __update_axes
    assert len(self.plots) == len(self.ydata)
AssertionError

Got len(self.ydata) = 60
len(self.plots) = 48 
There is 10 DoFs in the model.

**Comment by EveCharbie** [comment]
I confirm that there is the same issue with plots in the example symmetry_by_mapping

**Comment by pariterre** [comment]
Fixed in #819
