### ISSUE TITLE
module 'bioviz' has no attribute '__version__'. Did you mean: '_version'?

### ISSUE THREAD

**Issue by taDachs** [pyomeca/bioptim#898]
Hey,
I am currently running into an issue when trying to run some of the examples. Here is a Dockerfile for reproduction:

```Dockerfile
FROM mambaorg/micromamba

# install apt deps, have to switch to root first
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
   ripgrep git git-lfs tldr curl libgl1-mesa-dev python3-venv python3 cmake \
   && rm -rf /var/lib/apt/lists/*
USER $MAMBA_USER


WORKDIR /home/$MAMBA_USER
# install bioptim + deps
RUN micromamba install -n base -y -c conda-forge biorbd bioviz python-graphviz vtk && \
  git clone https://github.com/pyomeca/bioptim.git && \
  cd bioptim && \
  git checkout Release_3.2.1 && \
  bash -c 'eval "$(micromamba shell hook --shell bash)" && micromamba activate && python setup.py install'
```

When installing bioptim this way, when I run the getting_started/pendulum.py examples I get the following error message after running the solver:

```
Traceback (most recent call last):
  File "/home/mambauser/bioptim/bioptim/examples/getting_started/pendulum.py", line 214, in <module>
    main()
  File "/home/mambauser/bioptim/bioptim/examples/getting_started/pendulum.py", line 163, in main
    sol.animate(n_frames=0, viewer=viewer, show_now=True)
  File "/opt/conda/lib/python3.12/site-packages/bioptim-3.2.1-py3.12.egg/bioptim/optimization/solution/solution.py", line 1259, in animate
    type(self.ocp.nlp[0].model).animate(
  File "/opt/conda/lib/python3.12/site-packages/bioptim-3.2.1-py3.12.egg/bioptim/models/biorbd/biorbd_model.py", line 746, in animate
    return animate_with_bioviz_for_loop(ocp, solution, show_now, show_tracked_markers, n_frames, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/bioptim-3.2.1-py3.12.egg/bioptim/models/biorbd/viewer_bioviz.py", line 44, in animate_with_bioviz_for_loop
    animate_with_bioviz(
  File "/opt/conda/lib/python3.12/site-packages/bioptim-3.2.1-py3.12.egg/bioptim/models/biorbd/viewer_bioviz.py", line 68, in animate_with_bioviz
    check_version(bioviz, "2.4.0", "2.5.0")
  File "/opt/conda/lib/python3.12/site-packages/bioptim-3.2.1-py3.12.egg/bioptim/misc/utils.py", line 22, in check_version
    ver = parse_version(tool_to_compare.__version__)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'bioviz' has no attribute '__version__'. Did you mean: '_version'?
```

I am struggling to find the correct version for use of bioviz. Here is my current environment:
<details>
  <summary>Mamba Environment</summary>

```
- _libgcc_mutex=0.1=conda_forge
- _openmp_mutex=4.5=2_gnu
- _x86_64-microarch-level=3=2_x86_64_v3
- aiohappyeyeballs=2.4.3=pyhd8ed1ab_0
- aiohttp=3.10.10=py312h178313f_0
- aiosignal=1.3.1=pyhd8ed1ab_0
- alsa-lib=1.2.12=h4ab18f5_0
- ampl-mp=3.1.0=h2cc385e_1006
- aom=3.9.1=hac33072_0
- atk-1.0=2.38.0=h04ea711_2
- attr=2.5.1=h166bdaf_1
- attrs=24.2.0=pyh71513ae_0
- biorbd=1.11.2=py312h2324e82_1
- bioviz=2.4.1=py312_h7900ff3_0
- blosc=1.21.6=hef167b5_0
- bottleneck=1.4.2=py312hc0a28a1_0
- brotli=1.1.0=hb9d3cd8_2
- brotli-bin=1.1.0=hb9d3cd8_2
- bzip2=1.0.8=h4bc722e_7
- c-ares=1.34.2=heb4867d_0
- ca-certificates=2024.8.30=hbcca054_0
- cairo=1.18.0=hebfffa5_3
- casadi=3.6.7=py312h0385bb2_0
- certifi=2024.8.30=pyhd8ed1ab_0
- contourpy=1.3.0=py312h68727a3_2
- cycler=0.12.1=pyhd8ed1ab_0
- dav1d=1.2.1=hd590300_0
- dbus=1.13.6=h5008d03_3
- double-conversion=3.3.0=h59595ed_0
- eigen=3.4.0=h00ab1b0_0
- et_xmlfile=2.0.0=pyhd8ed1ab_0
- expat=2.6.3=h5888daf_0
- ezc3d=1.5.11=py312_python3_h2e0938c_3
- ffmpeg=7.1.0=gpl_h8657690_700
- font-ttf-dejavu-sans-mono=2.37=hab24e00_0
- font-ttf-inconsolata=3.000=h77eed37_0
- font-ttf-source-code-pro=2.038=h77eed37_0
- font-ttf-ubuntu=0.83=h77eed37_3
- fontconfig=2.15.0=h7e30c49_1
- fonts-conda-ecosystem=1=0
- fonts-conda-forge=1=0
- fonttools=4.54.1=py312h178313f_1
- freetype=2.12.1=h267a509_2
- fribidi=1.0.10=h36c2ea0_0
- frozenlist=1.5.0=py312h66e93f0_0
- gdk-pixbuf=2.42.12=hb9ae30d_0
- gettext=0.22.5=he02047a_3
- gettext-tools=0.22.5=he02047a_3
- gl2ps=1.4.2=hae5d5c5_1
- glew=2.1.0=h9c3ff4c_2
- glib=2.82.2=h44428e9_0
- glib-tools=2.82.2=h4833e2c_0
- gmp=6.3.0=hac33072_2
- graphite2=1.3.13=h59595ed_1003
- graphviz=12.0.0=hba01fac_0
- gst-plugins-base=1.24.7=h0a52356_0
- gstreamer=1.24.7=hf3bb09a_0
- gtk2=2.24.33=h6470451_5
- gts=0.7.6=h977cf35_4
- harfbuzz=9.0.0=hda332d3_1
- hdf4=4.2.15=h2a13503_7
- hdf5=1.14.4=nompi_h2d575fe_101
- icu=75.1=he02047a_0
- idna=3.10=pyhd8ed1ab_0
- ipopt=3.14.16=h122424a_10
- jsoncpp=1.9.6=h84d6215_0
- keyutils=1.6.1=h166bdaf_0
- kiwisolver=1.4.7=py312h68727a3_0
- krb5=1.21.3=h659f571_0
- lame=3.100=h166bdaf_1003
- lcms2=2.16=hb7c19ff_0
- ld_impl_linux-64=2.43=h712a8e2_2
- lerc=4.0.0=h27087fc_0
- libabseil=20240722.0=cxx17_h5888daf_1
- libaec=1.1.3=h59595ed_0
- libasprintf=0.22.5=he8f35ee_3
- libasprintf-devel=0.22.5=he8f35ee_3
- libass=0.17.3=h1dc1e6a_0
- libblas=3.9.0=25_linux64_openblas
- libblasfeo=0.1.3=had105d5_303
- libbrotlicommon=1.1.0=hb9d3cd8_2
- libbrotlidec=1.1.0=hb9d3cd8_2
- libbrotlienc=1.1.0=hb9d3cd8_2
- libcap=2.69=h0f662aa_0
- libcblas=3.9.0=25_linux64_openblas
- libclang-cpp15=15.0.7=default_h127d8a8_5
- libclang-cpp19.1=19.1.3=default_hb5137d0_0
- libclang13=19.1.3=default_h9c6a7e4_0
- libcups=2.3.3=h4637d8d_4
- libcurl=8.10.1=hbbe4b11_0
- libdeflate=1.22=hb9d3cd8_0
- libdrm=2.4.123=hb9d3cd8_0
- libedit=3.1.20191231=he28a2e2_2
- libegl=1.7.0=ha4b6fd6_0
- libev=4.33=hd590300_2
- libevent=2.1.12=hf998b51_1
- libexpat=2.6.3=h5888daf_0
- libfatrop=0.0.4=h5888daf_0
- libffi=3.4.2=h7f98852_5
- libflac=1.4.3=h59595ed_0
- libgcc=14.2.0=h77fa898_1
- libgcc-ng=14.2.0=h69a702a_1
- libgcrypt=1.11.0=h4ab18f5_1
- libgd=2.3.3=hd3e95f3_10
- libgettextpo=0.22.5=he02047a_3
- libgettextpo-devel=0.22.5=he02047a_3
- libgfortran=14.2.0=h69a702a_1
- libgfortran-ng=14.2.0=h69a702a_1
- libgfortran5=14.2.0=hd5240d6_1
- libgl=1.7.0=ha4b6fd6_0
- libglib=2.82.2=h2ff4ddf_0
- libglu=9.0.0=ha6d2627_1004
- libglvnd=1.7.0=ha4b6fd6_0
- libglx=1.7.0=ha4b6fd6_0
- libgomp=14.2.0=h77fa898_1
- libgpg-error=1.50=h4f305b6_0
- libhwloc=2.11.2=default_he43201b_1000
- libiconv=1.17=hd590300_2
- libjpeg-turbo=3.0.0=hd590300_1
- liblapack=3.9.0=25_linux64_openblas
- libllvm15=15.0.7=hb3ce162_4
- libllvm19=19.1.3=ha7bfdaf_0
- libnetcdf=4.9.2=nompi_h2564987_115
- libnghttp2=1.64.0=h161d5f1_0
- libnsl=2.0.1=hd590300_0
- libogg=1.3.5=h4ab18f5_0
- libopenblas=0.3.28=pthreads_h94d23a6_0
- libopenvino=2024.4.0=hac27bb2_2
- libopenvino-auto-batch-plugin=2024.4.0=h4d9b6c2_2
- libopenvino-auto-plugin=2024.4.0=h4d9b6c2_2
- libopenvino-hetero-plugin=2024.4.0=h3f63f65_2
- libopenvino-intel-cpu-plugin=2024.4.0=hac27bb2_2
- libopenvino-intel-gpu-plugin=2024.4.0=hac27bb2_2
- libopenvino-intel-npu-plugin=2024.4.0=hac27bb2_2
- libopenvino-ir-frontend=2024.4.0=h3f63f65_2
- libopenvino-onnx-frontend=2024.4.0=h5c8f2c3_2
- libopenvino-paddle-frontend=2024.4.0=h5c8f2c3_2
- libopenvino-pytorch-frontend=2024.4.0=h5888daf_2
- libopenvino-tensorflow-frontend=2024.4.0=h6481b9d_2
- libopenvino-tensorflow-lite-frontend=2024.4.0=h5888daf_2
- libopus=1.3.1=h7f98852_1
- libosqp=0.6.3=h5888daf_1
- libpciaccess=0.18=hd590300_0
- libpng=1.6.44=hadc24fc_0
- libpq=16.4=h2d7952a_3
- libprotobuf=5.28.2=h5b01275_0
- libqdldl=0.1.7=hcb278e6_0
- librsvg=2.58.4=hc0ffecb_0
- libscotch=7.0.4=h2fe6a88_5
- libsndfile=1.2.2=hc60ed4a_1
- libspral=2024.05.08=h2b245be_4
- libsqlite=3.47.0=hadc24fc_1
- libssh2=1.11.0=h0841786_0
- libstdcxx=14.2.0=hc0a3c3a_1
- libstdcxx-ng=14.2.0=h4852527_1
- libsystemd0=256.7=h2774228_1
- libtheora=1.1.1=h4ab18f5_1006
- libtiff=4.7.0=he137b08_1
- libuuid=2.38.1=h0b41bf4_0
- libva=2.22.0=h8a09558_1
- libvorbis=1.3.7=h9c3ff4c_0
- libvpx=1.14.1=hac33072_0
- libwebp-base=1.4.0=hd590300_0
- libxcb=1.16=hb9d3cd8_1
- libxcrypt=4.4.36=hd590300_1
- libxkbcommon=1.7.0=h2c5496b_1
- libxml2=2.13.4=hb346dea_2
- libzip=1.11.2=h6991a6a_0
- libzlib=1.3.1=hb9d3cd8_2
- loguru=0.7.2=py312h7900ff3_2
- lz4-c=1.9.4=hcb278e6_0
- matplotlib-base=3.9.2=py312hd3ec401_1
- metis=5.1.0=hd0bcaf9_1007
- mpg123=1.32.9=hc50e24c_0
- msgpack-python=1.1.0=py312h68727a3_0
- multidict=6.1.0=py312h178313f_1
- mumps-include=5.7.3=ha770c72_5
- mumps-seq=5.7.3=h27a6a8b_0
- munkres=1.1.4=pyh9f0ad1d_0
- mysql-common=9.0.1=h266115a_2
- mysql-libs=9.0.1=he0572af_2
- ncurses=6.5=he02047a_1
- nlohmann_json=3.11.3=he02047a_1
- nspr=4.36=h5888daf_0
- nss=3.106=hdf54f9c_0
- numpy=2.1.3=py312h58c1407_0
- ocl-icd=2.3.2=hd590300_1
- openh264=2.4.1=h59595ed_0
- openjpeg=2.5.2=h488ebb8_0
- openpyxl=3.1.5=py312h710cb58_1
- openssl=3.3.2=hb9d3cd8_0
- packaging=24.1=pyhd8ed1ab_0
- pandas=2.2.3=py312hf9745cd_1
- pango=1.54.0=h4c5309f_1
- pcre2=10.44=hba22ea6_2
- pillow=10.4.0=py312h56024de_1
- pip=24.3.1=pyh8b19718_0
- pixman=0.43.2=h59595ed_0
- ply=3.11=pyhd8ed1ab_2
- proj=9.5.0=h12925eb_0
- propcache=0.2.0=py312h66e93f0_2
- proxsuite=0.6.7=py312h68727a3_1
- pthread-stubs=0.4=hb9d3cd8_1002
- pugixml=1.14=h59595ed_0
- pulseaudio-client=17.0=hb77b528_0
- pyomeca=2024.0.1=pyhd8ed1ab_0
- pyparsing=3.2.0=pyhd8ed1ab_1
- pyqt=5.15.9=py312h949fe66_5
- pyqt5-sip=12.12.2=py312h30efb56_5
- python=3.12.7=hc5c86c4_0_cpython
- python-dateutil=2.9.0=pyhd8ed1ab_0
- python-graphviz=0.20.3=pyhe28f650_1
- python-tzdata=2024.2=pyhd8ed1ab_0
- python_abi=3.12=5_cp312
- pytz=2024.1=pyhd8ed1ab_0
- qhull=2020.2=h434a139_5
- qt-main=5.15.8=h3155989_26
- qt6-main=6.7.2=hadfd74e_5
- rbdl=3.3.1=h84d6215_4
- readline=8.2=h8228510_1
- scipy=1.14.1=py312h62794b6_1
- setuptools=75.3.0=pyhd8ed1ab_0
- simde=0.8.2=h84d6215_0
- sip=6.7.12=py312h30efb56_0
- six=1.16.0=pyh6c4a22f_0
- snappy=1.2.1=ha2e4443_0
- sqlite=3.47.0=h9eae976_1
- svt-av1=2.2.1=h5888daf_0
- tbb=2022.0.0=hceb3a55_0
- tbb-devel=2022.0.0=h1f99690_0
- tinyxml=2.6.2=h4bd325d_2
- tinyxml2=10.0.0=h59595ed_0
- tk=8.6.13=noxft_h4845f30_101
- toml=0.10.2=pyhd8ed1ab_0
- tomli=2.0.2=pyhd8ed1ab_0
- tzdata=2024b=hc8b5060_0
- unicodedata2=15.1.0=py312h66e93f0_1
- unixodbc=2.3.12=h661eb56_0
- utfcpp=4.0.6=h005c6e1_0
- vtk=9.3.1=qt_py312h3d4e8c9_209
- vtk-base=9.3.1=qt_py312h1176116_209
- vtk-io-ffmpeg=9.3.1=qt_py312he1e5eab_209
- wayland=1.23.1=h3e06ad9_0
- wayland-protocols=1.37=hd8ed1ab_0
- wheel=0.44.0=pyhd8ed1ab_0
- wslink=2.2.1=pyhd8ed1ab_0
- x264=1!164.3095=h166bdaf_2
- x265=3.5=h924138e_3
- xarray=2024.10.0=pyhd8ed1ab_0
- xcb-util=0.4.1=hb711507_2
- xcb-util-cursor=0.1.5=hb9d3cd8_0
- xcb-util-image=0.4.0=hb711507_2
- xcb-util-keysyms=0.4.1=hb711507_0
- xcb-util-renderutil=0.3.10=hb711507_0
- xcb-util-wm=0.4.2=hb711507_0
- xkeyboard-config=2.42=h4ab18f5_0
- xorg-fixesproto=5.0=hb9d3cd8_1003
- xorg-inputproto=2.3.2=hb9d3cd8_1003
- xorg-kbproto=1.0.7=hb9d3cd8_1003
- xorg-libice=1.1.1=hb9d3cd8_1
- xorg-libsm=1.2.4=he73a12e_1
- xorg-libx11=1.8.9=hb711507_1
- xorg-libxau=1.0.11=hb9d3cd8_1
- xorg-libxdmcp=1.1.5=hb9d3cd8_0
- xorg-libxext=1.3.4=h0b41bf4_2
- xorg-libxfixes=5.0.3=h7f98852_1004
- xorg-libxi=1.7.10=h4bc722e_1
- xorg-libxrender=0.9.11=hd590300_0
- xorg-libxt=1.3.0=hd590300_1
- xorg-libxtst=1.2.5=h4bc722e_0
- xorg-libxxf86vm=1.1.5=hb9d3cd8_2
- xorg-recordproto=1.14.2=hb9d3cd8_1003
- xorg-renderproto=0.11.1=hb9d3cd8_1003
- xorg-xextproto=7.3.0=hb9d3cd8_1004
- xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1004
- xorg-xproto=7.0.31=hb9d3cd8_1008
- xz=5.2.6=h166bdaf_0
- yarl=1.16.0=py312h66e93f0_0
- zlib=1.3.1=hb9d3cd8_2
- zstd=1.5.6=ha6fb4c9_0
```
</details>

**Comment by pariterre** [comment]
I've just push a version on bioviz which should fix this problem. This should take about half a day so everything gets push to conda, when bioviz 2.4.2 is available, please let me know if it works!

**Comment by taDachs** [comment]
fixed it, thanks
